In [6]:
import pandas as pd
import numpy as np

In [15]:
testDF = pd.read_csv('../datasets/mp_ONS_decsriptors_v3.csv')
testDF.head(2)

smiles       mp    ALogp2      AMR       apol  naAromAtom  nAromBond  \
0  C1(CCC1)C -161.505  0.127164  20.3505  15.467930           0          0   
1     CN(C)C -117.040  0.102464  19.9881  12.381137           0          0   

   nAtom  nHeavyAtom  nH  ...       AMW    WTPT-1    WTPT-2    WTPT-3  WTPT-4  \
0     15           5  10  ...  4.671883  9.414511  1.882902  0.000000     0.0   
1     13           4   9  ...  4.544115  6.732051  1.683013  2.732051     0.0   

     WTPT-5  WPATH  WPOL  XLogP  Zagreb  
0  0.000000     16     1  2.784      22  
1  2.732051      9     0  0.063      12  

[2 rows x 1444 columns]

In [25]:
ds = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(ds)

a    1
b    2
c    3
d    4
dtype: int64


In [39]:
ds['a':'b']

a    1
b    2
dtype: int64

In [43]:
ds[ ['a','c'] ]

a    1
c    3
dtype: int64

In [42]:
fc=testDF[ ['smiles', 'mp']]
fc

smiles          mp
0                         C1(CCC1)C -161.505000
1                            CN(C)C -117.040000
2                     ClC(Cl)(Cl)Cl  -22.987500
3                               C#C  -80.750000
4        C(=C(Cl)Cl)(C(Cl)(Cl)Cl)Cl  -72.950000
...                             ...         ...
2699         CC1=CC(=O)c2ccccc2C1=O  104.250000
2700                    CCCC(=O)OCC  -94.250000
2701        O=N(=O)c1ccc(C(=O)O)cc1  240.400000
2702  O=C(O)c1cc(ccc1O)c1ccc(F)cc1F  213.498000
2703          c1c(cc(c(c1Cl)O)Cl)Cl   68.142857

[2704 rows x 2 columns]

In [45]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
mask = arr%2 == 0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [74]:
arr[ arr%2 == 0 ]

array([0, 2, 4, 6, 8])

In [52]:
ds = testDF['mp']
ds.shape

(2704,)

0       False
1       False
2       False
3       False
4       False
        ...  
2699     True
2700    False
2701     True
2702     True
2703     True
Name: mp, Length: 2704, dtype: bool

In [55]:
positive.shape

(2063,)