# Numpy intro

In [44]:
import numpy as np

In [45]:
ndarr=np.array([[1,2,3],[4,5,6]], dtype=np.int8)
ndarr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

## find bigger number

In [50]:
def find_big_num (*args):
    return(max(args))
result1 = find_big_num(2,3,6,7,3,5,10)
result1
result2 = find_big_num(234,54,345,1000)
result2

1000

## bacis properties

### numpy create methods https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

### numpy.array() & numpy.arange() & ndarray attributes( size, shape, ndim, dtype, nbytes, itemsize)   
https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes

In [51]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)
print(a3)
print(a3.shape)
print(a3.size)
print(a3.nbytes)
a4 = np.array([[0,2,3],[0,5,6],[0,8,9]],dtype=np.bool)
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
9
[[False  True  True]
 [False  True  True]
 [False  True  True]]


In [52]:
a5 = np.arange(0,10,2)# start,stop,step
print(a5)
print(a5.shape)
print(a5.size)
print(a5.nbytes)
print(a5.ndim)

[0 2 4 6 8]
(5,)
5
20
1


### arrays algebra point to point

In [53]:
print('a3= ',a3)
a6 = np.array([1,2,3])
print('a3 + a6 = ',a3+a6)
print('a6*3 = ',a6*2)

a3=  [[1 2 3]
 [4 5 6]
 [7 8 9]]
a3 + a6 =  [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
a6*3 =  [2 4 6]


In [54]:
print(a3.dot(a6))
print(a6.dot(a3))

[14 32 50]
[30 36 42]


### indexid & slicing

In [75]:
a8 =np.arange(1,13).reshape(4,3)
print(a8)
#[row start:stop:step ,column start:stop:step]
print('all elements without middle column',a8[0::1,0::2])
print('all elements without first & second column',a8[0::1,2::])
print('all elements without second & third row',a8[0::2,0::1])
print('only second row & second column',a8[1::,1::])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
all elements without middle column [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]
all elements without first & second column [[ 3]
 [ 6]
 [ 9]
 [12]]
all elements without second & third row [[1 2 3]
 [7 8 9]]
only second row & second column [[ 5  6]
 [ 8  9]
 [11 12]]


### masking

In [83]:
a9=a8[a8%2==0]
print (a8)
print(a9)
a10=a8[a8%2!=0]
print(a10)
a11=a8[a8<=6]
print(a11)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 2  4  6  8 10 12]
[ 1  3  5  7  9 11]
[1 2 3 4 5 6]
