In [1]:
import numpy as np

In [17]:
arr1 = np.linspace(1,100,num=10,dtype=np.int8);
arr1

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100], dtype=int8)

In [20]:
arr2 = arr1*2
arr2

array([   2,   24,   46,   68,   90,  112, -122, -100,  -78,  -56],
      dtype=int8)

In [19]:
a2 = np.arange(1,10)
a2.shape

(9,)

In [13]:
a3 = a2.reshape((3,3))
print(a2)
print(a3)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
arr = np.arange(1,10)
print(arr)
arr[-1]

[1 2 3 4 5 6 7 8 9]


9

In [49]:
arr = arr.reshape(3,3)
print(arr)
arr2 = arr[0::2, 0::2]
arr2

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 3],
       [7, 9]])

In [50]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr4 = arr3>2
arr4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])